import Link from "next/link";
import { ProjectForm } from "@/components/operations/project-form";
import { requirePermission } from "@/lib/auth/context";
import { createAdminClient } from "@/lib/supabase/admin";
import { getOperationsOverview } from "@/lib/operations";
import { createProjectAction, updateProjectAction } from "../operations-actions";

export const dynamic = "force-dynamic";
export default async function ProjectsPage() { const context = await requirePermission("clients.read"); const canManage = context.permissions.includes("clients.manage"); const [overview, clientsResult, usersResult] = await Promise.all([getOperationsOverview(context), canManage ? createAdminClient().from("clients").select("id,name").eq("status", "active").is("archived_at", null).order("name") : Promise.resolve({ data: [] }), canManage ? createAdminClient().from("profiles").select("id,full_name").eq("status", "active").order("full_name") : Promise.resolve({ data: [] })]); const clients = clientsResult.data ?? []; const users = (usersResult.data ?? []).map((user) => ({ id: user.id, name: user.full_name })); return <div className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs tracking-[.16em] text-[#8d8f88]">OPERATIONS</p><h1 className="mt-3 text-3xl tracking-tight">Projects</h1></div>{canManage && <details className="border border-[#343630] px-4 py-2 text-sm"><summary className="cursor-pointer">Create project</summary><div className="mt-4 w-[min(720px,80vw)]"><ProjectForm action={createProjectAction} clients={clients} users={users}/></div></details>}</div><div className="mt-10 grid gap-px border border-[#2b2d29] bg-[#2b2d29] md:grid-cols-2">{overview.projects.length ? overview.projects.map((project) => <div className="bg-[#171815] p-6" key={project.id}><div className="flex items-start justify-between gap-4"><div><Link href={`/clients/${project.clients?.slug}`} className="font-medium transition hover:text-[#c8f54b]">{project.name}</Link><p className="mt-2 text-sm text-[#898b84]">{project.clients?.name ?? "Client"}{project.owner?.full_name ? ` · ${project.owner.full_name}` : ""}</p></div><span className="border border-[#343630] px-2 py-1 text-[11px] tracking-[.1em]">{project.status.replace("_", " ")}</span></div><p className="mt-5 text-sm text-[#a8a9a2]">{project.description || "No project description yet."}</p><div className="mt-7 flex items-center justify-between text-xs"><span className="text-[#b8bd9f]">{project.progress.complete}/{project.progress.total} tasks complete</span><span className="text-[#777971]">{project.progress.percent}%</span></div><div className="mt-2 h-1 bg-[#2b2d29]"><div className="h-full bg-[#c8f54b]" style={{ width: `${project.progress.percent}%` }}/></div><p className="mt-4 text-xs text-[#777971]">Due {project.due_date ?? "not set"}</p>{canManage && <details className="mt-4"><summary className="cursor-pointer text-xs text-[#b8bd9f]">Edit project</summary><div className="mt-3"><ProjectForm action={updateProjectAction} project={project} clients={clients} users={users}/></div></details>}</div>) : <p className="bg-[#171815] p-8 text-sm text-[#898b84] md:col-span-2">No projects yet. {canManage ? "Create a project under an active client to plan deliverables." : "Projects for your assigned clients will appear here."}</p>}</div></div>; }
