"use server";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createServerClient } from "@/lib/supabase/server";
import { authCallbackUrl } from "@/lib/site-url";
import { createAdminClient } from "@/lib/supabase/admin";
export type AuthFormState={error?:string;success?:string};
const emailSchema=z.string().trim().email(), passwordSchema=z.string().min(12,"Use at least 12 characters.").max(256);
export async function requestPasswordReset(_previous:AuthFormState,formData:FormData):Promise<AuthFormState>{try{const email=emailSchema.parse(String(formData.get("email")??""));const supabase=await createServerClient();if(!supabase)throw new Error("Authentication is not configured.");const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:authCallbackUrl("/auth/reset-password")});if(error)throw new Error("Unable to send a recovery email.");return {success:"If an account exists for that address, a recovery link has been sent."};}catch(error){return {error:error instanceof Error?error.message:"Unable to request password reset."};}}
async function completeInvitationPasswordSetup(userId:string){const admin=createAdminClient();const {data:profile,error:profileError}=await admin.from("profiles").select("status").eq("id",userId).single();if(profileError)throw new Error("Unable to complete account setup.");if(profile.status!=="invited")return;const {data:auth,error:authError}=await admin.auth.admin.getUserById(userId);if(authError||!auth.user)throw new Error("Unable to complete account setup.");const metadata=auth.user.app_metadata??{};if(metadata.move_first_initial_password_required!==true)throw new Error("Invitation setup is not valid.");const {error:metadataError}=await admin.auth.admin.updateUserById(userId,{app_metadata:{...metadata,move_first_initial_password_required:false}});if(metadataError)throw new Error("Unable to complete account setup.");const {error:activateError}=await admin.rpc("app_activate_invited_user",{target_user_id:userId});if(activateError)throw new Error("Unable to complete account setup.");}
export async function updatePassword(_previous:AuthFormState,formData:FormData):Promise<AuthFormState>{try{const password=passwordSchema.parse(String(formData.get("password")??""));if(password!==String(formData.get("confirmation")??""))throw new Error("Passwords do not match.");const supabase=await createServerClient();if(!supabase)throw new Error("Authentication is not configured.");const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Your recovery session has expired. Request another link.");const {error}=await supabase.auth.updateUser({password});if(error)throw new Error(error.message);await completeInvitationPasswordSetup(user.id);await supabase.auth.signOut();}catch(error){return {error:error instanceof Error?error.message:"Unable to reset password."};}redirect("/login?reset=complete");}
