import { NextResponse } from "next/server";
import type { EmailOtpType } from "@supabase/supabase-js";
import { createClient } from "@supabase/supabase-js";
import { createServerClient } from "@/lib/supabase/server";
import { APP_HOME } from "@/lib/navigation";

async function recordLogin(accessToken:string){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)return {error:new Error("Authentication is not configured."),authorizationPresent:false,authorizationMatchesIssuedSession:false,contextResolved:false,contextStatus:null,contextError:null};let authorizationPresent=false,authorizationMatchesIssuedSession=false;const authenticated=createClient(url,key,{accessToken:async()=>accessToken,auth:{autoRefreshToken:false,persistSession:false},global:{fetch:async(input,init)=>{const headers=new Headers(init?.headers);const authorization=headers.get("authorization");authorizationPresent=Boolean(authorization);authorizationMatchesIssuedSession=authorization===`Bearer ${accessToken}`;return fetch(input,init);}}});const result=await authenticated.rpc("app_record_login");const context=result.error?await authenticated.rpc("app_current_context"):null;return {...result,authorizationPresent,authorizationMatchesIssuedSession,contextResolved:Boolean(context?.data?.[0]),contextStatus:context?.data?.[0]?.status??null,contextError:context?.error??null};}

function errorCategory(error:unknown){if(!error)return null;if(error instanceof Error){if(error.message==="Account is not active")return "account_not_active";if(error.message==="Authentication is not configured.")return "configuration";return error.name||"error";}if(typeof error==="object"&&error){if("code" in error)return typeof error.code==="string"?error.code:"database_error";if("message" in error&&typeof error.message==="string"){if(/invalid api key/i.test(error.message))return "invalid_api_key";if(/jwt|token/i.test(error.message))return "invalid_jwt";if(/permission|unauthori[sz]ed/i.test(error.message))return "authorization";return "gateway_error";}}return "unknown";}
function errorShape(error:unknown){return {type:typeof error,isError:error instanceof Error,name:error instanceof Error?error.name:null,keys:typeof error==="object"&&error?Object.keys(error).sort():[]};}
function logCallbackFailure(stage:string,result:Awaited<ReturnType<typeof recordLogin>>){console.info("move_first_auth_callback_failure",{stage,authorizationPresent:result.authorizationPresent,authorizationMatchesIssuedSession:result.authorizationMatchesIssuedSession,contextResolved:result.contextResolved,contextStatus:result.contextStatus,rpcErrorCategory:errorCategory(result.error),rpcErrorShape:errorShape(result.error),contextErrorCategory:errorCategory(result.contextError),contextErrorShape:errorShape(result.contextError)});}

export async function GET(request:Request){const url=new URL(request.url);const code=url.searchParams.get("code"),tokenHash=url.searchParams.get("token_hash"),type=url.searchParams.get("type"),next=url.searchParams.get("next");if(!code&&!tokenHash)return NextResponse.redirect(new URL("/login?error=link",request.url));const supabase=await createServerClient();if(!supabase)return NextResponse.redirect(new URL("/login?error=configuration",request.url));if(tokenHash){if(type!=="recovery")return NextResponse.redirect(new URL("/login?error=link",request.url));const {data,error}=await supabase.auth.verifyOtp({token_hash:tokenHash,type:type as EmailOtpType});if(error||!data.session)return NextResponse.redirect(new URL("/login?error=link",request.url));const login=await recordLogin(data.session.access_token);if(login.error){logCallbackFailure("recovery",login);await supabase.auth.signOut();return NextResponse.redirect(new URL("/login?error=inactive",request.url));}return NextResponse.redirect(new URL("/auth/reset-password",request.url));}const {data,error}=await supabase.auth.exchangeCodeForSession(code!);if(error||!data.session)return NextResponse.redirect(new URL("/login?error=link",request.url));if(next&&next.startsWith("/")&&!next.startsWith("//"))return NextResponse.redirect(new URL(next,request.url));const login=await recordLogin(data.session.access_token);if(login.error){logCallbackFailure("code",login);await supabase.auth.signOut();return NextResponse.redirect(new URL("/login?error=inactive",request.url));}return NextResponse.redirect(new URL(APP_HOME,request.url));}
export async function POST(request:Request){const form=await request.formData();const email=String(form.get("email")??"");const password=String(form.get("password")??"");const supabase=await createServerClient();if(!supabase)return NextResponse.redirect(new URL("/login?error=configuration",request.url));const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error||!data.session)return NextResponse.redirect(new URL("/login?error=credentials",request.url));const login=await recordLogin(data.session.access_token);if(login.error){logCallbackFailure("password",login);await supabase.auth.signOut();return NextResponse.redirect(new URL("/login?error=inactive",request.url));}return NextResponse.redirect(new URL(APP_HOME,request.url));}
