import { afterAll, beforeAll, describe, expect, it } from "vitest";
const enabled=process.env.RUN_SUPABASE_INTEGRATION==="true", suite=enabled?describe:describe.skip;
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY!,anonKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const email=`move-first-rls-${Date.now()}@example.invalid`,password="Temporary-only-test-password-123";
let userId="", token="", refreshToken="", assignedClientId="", unassignedClientId="";
const serviceHeaders={apikey:serviceKey,Authorization:`Bearer ${serviceKey}`,"Content-Type":"application/json"};
async function request(path:string,init:RequestInit={},headers:Record<string,string>=serviceHeaders){const response=await fetch(`${url}${path}`,{...init,headers:{...headers,...init.headers}});const body=await response.json().catch(()=>null);return {response,body};}
suite("linked Supabase RLS",()=>{
  beforeAll(async()=>{if(!url||!serviceKey||!anonKey)throw new Error("Supabase test configuration is missing.");const created=await request("/auth/v1/admin/users",{method:"POST",body:JSON.stringify({email,password,email_confirm:true})});if(!created.response.ok)throw new Error("Unable to create disposable RLS test user.");userId=created.body.id;const role=await request("/rest/v1/roles?select=id&key=eq.MEMBER");const permission=await request("/rest/v1/permissions?select=id&key=eq.agents.manage");await request("/rest/v1/profiles",{method:"POST",body:JSON.stringify({id:userId,full_name:"RLS Test",role_id:role.body[0].id,status:"active"})});await request("/rest/v1/user_permissions",{method:"POST",body:JSON.stringify({user_id:userId,permission_id:permission.body[0].id})});const assigned=await request("/rest/v1/clients",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({slug:`rls-assigned-${Date.now()}`,name:"Assigned test client"})});const unassigned=await request("/rest/v1/clients",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({slug:`rls-unassigned-${Date.now()}`,name:"Unassigned test client"})});assignedClientId=assigned.body[0].id;unassignedClientId=unassigned.body[0].id;await request("/rest/v1/client_members",{method:"POST",body:JSON.stringify({client_id:assignedClientId,user_id:userId})});const login=await request("/auth/v1/token?grant_type=password",{method:"POST",body:JSON.stringify({email,password})},{apikey:anonKey,"Content-Type":"application/json"});if(!login.response.ok)throw new Error("Unable to sign in disposable RLS test user.");token=login.body.access_token;refreshToken=login.body.refresh_token;});
  afterAll(async()=>{if(assignedClientId)await request(`/rest/v1/clients?id=eq.${assignedClientId}`,{method:"DELETE"});if(unassignedClientId)await request(`/rest/v1/clients?id=eq.${unassignedClientId}`,{method:"DELETE"});if(userId)await request(`/auth/v1/admin/users/${userId}`,{method:"DELETE"});});
  it("denies unauthorized writes and protected lookup reads",async()=>{const headers={apikey:anonKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"};const write=await request("/rest/v1/clients",{method:"POST",body:JSON.stringify({slug:"forbidden",name:"Forbidden"})},headers);expect(write.response.ok).toBe(false);const read=await request("/rest/v1/roles?select=id",{},headers);expect(read.response.ok).toBe(false);});
  it("returns an assigned client and blocks slug/UUID manipulation for an unassigned client",async()=>{const headers={apikey:anonKey,Authorization:`Bearer ${token}`};const assigned=await request(`/rest/v1/clients?select=id&id=eq.${assignedClientId}`,{},headers);const unassigned=await request(`/rest/v1/clients?select=id&id=eq.${unassignedClientId}`,{},headers);expect(assigned.body).toHaveLength(1);expect(unassigned.body).toEqual([]);});
  it("denies a disabled user with a direct permission and revokes refresh sessions",async()=>{await request(`/rest/v1/profiles?id=eq.${userId}`,{method:"PATCH",body:JSON.stringify({status:"disabled"})});const result=await request("/rest/v1/rpc/app_has_permission",{method:"POST",body:JSON.stringify({required_key:"agents.manage"})},{apikey:anonKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"});expect(result.response.ok).toBe(true);expect(result.body).toBe(false);const refresh=await request("/auth/v1/token?grant_type=refresh_token",{method:"POST",body:JSON.stringify({refresh_token:refreshToken})},{apikey:anonKey,"Content-Type":"application/json"});expect(refresh.response.ok).toBe(false);});
});
