import { notFound } from "next/navigation";
import { getCurrentContext } from "@/lib/auth/context";
import { canAccessClient } from "@/lib/auth/scope";
import { createAdminClient } from "@/lib/supabase/admin";
import { submitTaskDeliverableAction, updateTaskAction } from "../../operations-actions";

export const dynamic = "force-dynamic";
export default async function TaskDetail({ params }: { params: Promise<{ id: string }> }) {
  const context = await getCurrentContext(); if (!context) notFound(); const { id } = await params; const admin = createAdminClient();
  const [{ data: task }, { data: submission }] = await Promise.all([
    admin.from("tasks").select("id,title,description,client_id,project_id,assignee_id,priority,status,due_date,created_at,clients(name,slug),projects(name),assignee:profiles!tasks_assignee_id_fkey(full_name)").eq("id", id).maybeSingle(),
    admin.from("task_submissions").select("id,submitted_by,submitted_at,external_url,note,submitted:profiles!task_submissions_submitted_by_fkey(full_name)").eq("task_id", id).maybeSingle(),
  ]);
  if (!task || !canAccessClient(context, task.client_id) || (context.user.role === "MEMBER" && task.assignee_id !== context.user.id)) notFound();
  const owner = context.permissions.includes("clients.manage");
  const client = Array.isArray(task.clients) ? task.clients[0] : task.clients; const project = Array.isArray(task.projects) ? task.projects[0] : task.projects; const assignee = Array.isArray(task.assignee) ? task.assignee[0] : task.assignee; const submittedBy = submission?.submitted && (Array.isArray(submission.submitted) ? submission.submitted[0] : submission.submitted);
  const statusForm = (status: "IN_PROGRESS" | "DONE") => <form action={updateTaskAction} className="inline"><input type="hidden" name="id" value={task.id}/><input type="hidden" name="title" value={task.title}/><input type="hidden" name="description" value={task.description ?? ""}/><input type="hidden" name="clientId" value={task.client_id}/><input type="hidden" name="projectId" value={task.project_id ?? ""}/><input type="hidden" name="assigneeId" value={task.assignee_id ?? ""}/><input type="hidden" name="priority" value={task.priority}/><input type="hidden" name="status" value={status}/><input type="hidden" name="dueDate" value={task.due_date ?? ""}/><button className="border border-[#343630] px-3 py-2 text-xs">{status === "DONE" ? "Mark done" : "Send back"}</button></form>;
  return <div className="mx-auto max-w-4xl px-5 py-10 sm:px-8"><p className="text-xs tracking-[.16em] text-[#8d8f88]">TASK WORKSPACE</p><h1 className="mt-3 text-3xl tracking-tight">{task.title}</h1><p className="mt-2 text-[#a8a9a2]">{client?.name ?? "Client"}{project?.name ? ` · ${project.name}` : ""}</p><div className="mt-8 grid gap-3 border-y border-[#2b2d29] py-5 text-sm sm:grid-cols-4"><div><p className="text-xs text-[#777971]">STATUS</p><p className="mt-1">{task.status.replace("_", " ")}</p></div><div><p className="text-xs text-[#777971]">ASSIGNEE</p><p className="mt-1">{assignee?.full_name ?? "Unassigned"}</p></div><div><p className="text-xs text-[#777971]">DUE</p><p className="mt-1">{task.due_date ?? "No deadline"}</p></div><div><p className="text-xs text-[#777971]">PRIORITY</p><p className="mt-1">{task.priority}</p></div></div><section className="mt-10"><h2 className="text-xs tracking-[.16em] text-[#a8a9a2]">INSTRUCTIONS</h2><p className="mt-4 whitespace-pre-wrap border border-[#2b2d29] bg-[#171815] p-5 text-sm leading-6">{task.description || "No instructions have been added yet."}</p></section>{owner && <section className="mt-10"><h2 className="text-xs tracking-[.16em] text-[#a8a9a2]">OWNER REVIEW</h2><div className="mt-4 flex gap-3">{task.status === "SUBMITTED" && statusForm("DONE")}{task.status === "SUBMITTED" && statusForm("IN_PROGRESS")}</div>{submission && <div className="mt-4 border border-[#2b2d29] bg-[#171815] p-5 text-sm"><p className="text-[#b8bd9f]">Submitted by {submittedBy?.full_name ?? "Member"} on {new Date(submission.submitted_at).toLocaleString()}</p>{submission.external_url && <p className="mt-3 break-all"><a className="text-[#c8f54b] underline" href={submission.external_url} target="_blank" rel="noreferrer">{submission.external_url}</a></p>}{submission.note && <p className="mt-3 whitespace-pre-wrap">{submission.note}</p>}</div>}</section>}{!owner && <section className="mt-10"><h2 className="text-xs tracking-[.16em] text-[#a8a9a2]">SUBMIT WORK</h2><form action={submitTaskDeliverableAction} className="mt-4 grid gap-4 border border-[#2b2d29] bg-[#171815] p-5"><input type="hidden" name="taskId" value={task.id}/><label className="text-xs text-[#b5b6ae]">External link (optional)<input name="externalUrl" type="url" placeholder="https://drive.google.com/..." className="mt-2 w-full border border-[#343630] bg-[#10110f] p-2.5"/></label><label className="text-xs text-[#b5b6ae]">Written response<textarea name="note" placeholder="Describe the completed work" className="mt-2 min-h-28 w-full border border-[#343630] bg-[#10110f] p-2.5"/></label><button className="justify-self-start bg-[#c8f54b] px-4 py-2 text-sm font-medium text-[#10110f]">Submit work</button></form></section>}</div>;
}
