import "server-only";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireOwner } from "@/lib/auth/guards";

const roleSchema = z.enum(["OWNER", "ADMIN", "MEMBER"]);
const accessSchema = z.object({ agentIds: z.array(z.string().uuid()).default([]), clientIds: z.array(z.string().uuid()).default([]) });
const updateAccessSchema = z.object({ role: roleSchema, agentIds: z.array(z.string().uuid()).default([]), clientIds: z.array(z.string().uuid()).default([]) });
export const inviteUserSchema = z.object({ fullName: z.string().trim().min(2).max(120), email: z.string().trim().email().max(255), role: roleSchema, jobTitle: z.string().trim().max(120).optional().or(z.literal("")), ...accessSchema.shape });
export type InviteUserInput = z.infer<typeof inviteUserSchema>;

async function roleId(key: z.infer<typeof roleSchema>) { const admin=createAdminClient(); const {data,error}=await admin.from("roles").select("id").eq("key",key).single(); if(error||!data) throw new Error("Role configuration is unavailable."); return data.id; }
async function audit(actorId:string,action:string,entityType:string,entityId:string,metadata:Record<string,unknown>={}) { const admin=createAdminClient(); const {error}=await admin.from("activity_logs").insert({actor_id:actorId,action,entity_type:entityType,entity_id:entityId,metadata}); if(error) throw new Error("Unable to record the administrative action."); }

export async function inviteUser(input: InviteUserInput, redirectTo: string) {
  const actor=await requireOwner(); const values=inviteUserSchema.parse(input); const admin=createAdminClient();
  const {data:invite,error:inviteError}=await admin.auth.admin.inviteUserByEmail(values.email,{redirectTo,data:{full_name:values.fullName}});
  if(inviteError||!invite.user) throw new Error(inviteError?.message ?? "Unable to send invitation.");
  const assignedRoleId=await roleId(values.role);
  const {error:profileError}=await admin.from("profiles").upsert({id:invite.user.id,full_name:values.fullName,job_title:values.jobTitle||null,role_id:assignedRoleId,status:"invited"});
  if(profileError) throw new Error("Invitation was created but the profile could not be provisioned.");
  if(values.agentIds.length) { const {error}=await admin.from("user_agent_access").upsert(values.agentIds.map(agent_id=>({user_id:invite.user.id,agent_id}))); if(error) throw new Error("Agent access could not be assigned."); }
  if(values.clientIds.length) { const {error}=await admin.from("client_members").upsert(values.clientIds.map(client_id=>({user_id:invite.user.id,client_id}))); if(error) throw new Error("Client access could not be assigned."); }
  await audit(actor.user.id,"OWNER_INVITED_USER","profile",invite.user.id,{role:values.role,agentCount:values.agentIds.length,clientCount:values.clientIds.length});
}

export async function setUserStatus(userId:string, status:"active"|"disabled") { const actor=await requireOwner(); if(userId===actor.user.id&&status==="disabled") throw new Error("An owner cannot deactivate their own account."); const admin=createAdminClient(); const {data:target,error:targetError}=await admin.from("profiles").select("role_id, roles!inner(key)").eq("id",userId).single(); if(targetError||!target) throw new Error("User not found."); if((target.roles as unknown as {key:string}).key==="OWNER"&&status==="disabled") throw new Error("Owner accounts cannot be deactivated here."); const {error}=await admin.from("profiles").update({status}).eq("id",userId); if(error) throw new Error("Unable to update user status."); await audit(actor.user.id,status==="disabled"?"USER_DEACTIVATED":"USER_ACTIVATED","profile",userId); }
export async function updateUserAccess(userId:string,input:{role:"OWNER"|"ADMIN"|"MEMBER";agentIds:string[];clientIds:string[]}){const actor=await requireOwner();const values=updateAccessSchema.parse(input);const admin=createAdminClient();const {data:target,error:targetError}=await admin.from("profiles").select("roles!inner(key)").eq("id",userId).single();if(targetError||!target)throw new Error("User not found.");const targetRole=(target.roles as unknown as {key:string}).key;if(targetRole==="OWNER"&&userId!==actor.user.id)throw new Error("Owner privileges cannot be changed here.");if(userId===actor.user.id&&values.role!=="OWNER")throw new Error("An owner cannot remove their own owner role.");const nextRoleId=await roleId(values.role);const {error:profileError}=await admin.from("profiles").update({role_id:nextRoleId}).eq("id",userId);if(profileError)throw new Error("Unable to update role.");const [{error:removeAgents},{error:removeClients}]=await Promise.all([admin.from("user_agent_access").delete().eq("user_id",userId),admin.from("client_members").delete().eq("user_id",userId)]);if(removeAgents||removeClients)throw new Error("Unable to replace access.");if(values.agentIds.length){const {error}=await admin.from("user_agent_access").insert(values.agentIds.map(agent_id=>({user_id:userId,agent_id})));if(error)throw new Error("Unable to save agent access.");}if(values.clientIds.length){const {error}=await admin.from("client_members").insert(values.clientIds.map(client_id=>({user_id:userId,client_id})));if(error)throw new Error("Unable to save client access.");}await audit(actor.user.id,"USER_ACCESS_UPDATED","profile",userId,{previousRole:targetRole,role:values.role,agentCount:values.agentIds.length,clientCount:values.clientIds.length});}
export async function deleteUser(userId:string){const actor=await requireOwner();if(userId===actor.user.id)throw new Error("An owner cannot delete their own account.");const admin=createAdminClient();const {data:target,error:targetError}=await admin.from("profiles").select("roles!inner(key)").eq("id",userId).single();if(targetError||!target)throw new Error("User not found.");if((target.roles as unknown as {key:string}).key==="OWNER")throw new Error("Owner accounts cannot be deleted here.");await audit(actor.user.id,"USER_DELETED","profile",userId);const {error}=await admin.auth.admin.deleteUser(userId,false);if(error)throw new Error("Unable to delete user.");}
